name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        php_version: "7.4"
        version: 2
  
    - name: Install wpps-scripts
      run: git clone https://github.com/wp-plugin-sidekick/wpps-scripts;

    - name: Run phpcs linting with WordPress Coding Standards
      run: cd wpps-scripts; sh phpcs.sh -p wp-plugin-sidekick -n WPPS -t wpps;
